# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

# Controller specific parameters
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

velocity_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - wheel_left_front_joint
      - wheel_left_back_joint
      - wheel_right_front_joint
      - wheel_right_back_joint
    interface_name: velocity


